### ISSUE TITLE
Use of semantic versioning and github tags

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/craftguide#10] opened 2016-12-09 22:05 UTC
I propose the use of [semantic versioning](http://semver.org/) and github tags.

The actual version of craftguide is incompatible with stable version of Minetest (0.4.14) and if someone want compatible version of mod is inconvenient search for commits.

I propose github tags, it's more easy for download, too.

(Note: I use bower and minetest bower to manage my mods. Semantic versioning and github tags will make my life easier, too :smiley:) 

## **Update**
**My suggestion isn't create versions tags like Minetest but create own version tags.**

**Comment by diogo-gomes** [comment] 2016-12-09 22:17
You can always start versioning, it's never late.

If you want I can do it for you.

**Comment by sofar** [comment] 2016-12-11 06:17
My advice is if someone needs a fixed version for 0.4.14, and the people maintaining it are willing to make it, is to just fork and make a `minetest-0.4.14` branch.

Tagging 0.4.14 on the master branch isn't the right idea imho.

**Comment by jubalh** [comment] 2016-12-16 01:53
I think using versioning is a good idea.
Also I dont see how it can be a lot more extra work. Basically its just one line to tag it.

**Comment by sofar** [comment] 2016-12-16 02:33
The problem is that a tag is wrong. minetest-0.4.14 is a tag in minetest, but we may end up having more than one change to stay compatible with 0.4.14, so it shouldn't be a tag in this project, but a branch instead.

And on top of that, I'm not willing to maintain it, nor is anyone else as far as I can see.

**Comment by kilbith** [comment] 2016-12-16 02:40
For information, the mod is again (normally) compatible with 0.4.14 since https://github.com/minetest-mods/craftguide/commit/298397. But needs checking.

**Comment by jubalh** [comment] 2016-12-16 03:11
I think the original reporter had the idea to more easily download the mods. Using tags and github releases this could be  easier, as it autogenerated tarballs at that time and not only from master. Anyways there is no guarantee things are maintained right now, but having an indication with which version it worked last/should work would be nice I think.

**Comment by sofar** [comment] 2016-12-16 03:19
While I agree with the general notion of tags making things easier for consumers, the problem is that in the case of minetest mods, it actually is harder. We expect you to follow master at all times and upgrade whenever possible, and almost all mods work better if you update all the time.

Putting a tag down is the wrong way to get everyone to update: people will just pull an old tag and complain things are broken. Without tags, everyone will use HEAD, which is what we want.

**Comment by diogo-gomes** [comment] 2016-12-17 16:49
**My suggestion isn't create versions tags like minetest but create own version tags.**

You can start with version 1.0.0 with actual master branch.

Other mods have own tags and it is a great tool for development too. You can create alpha, beta, release candidates, etc.

If a gamer found a bug, he can simple downgrade to a compatible/stable version.

I know it's a simple mod but it can scale and version control is a bump for that

**Comment by jubalh** [comment] 2016-12-18 10:00
@sofar I see your point. But some distributions started to package the mods. So if you would have tags, the distributions packagers tools would get notified when there is a new version. So the packager would create a new version and people could download it using their package manager.
I understand that people git cloning and always pulling newest sources is best, but there are also people who are not familiar with such processes and only install via their package manager.

**Comment by SnarkBoojum** [comment] 2017-03-13 08:36
Hi, let me shime in : I would like to package craftguide for Debian, but I don't see anything really published apart from random commits. While I could package that, it basically means I'm throwing a dice at packaging an known-broken commit, while a versioned one means it's known to at least work in some cases.

So please, tag some releases  as @jubalh was advising : that means any packager would know something is good enough, and it also means we can automatically detect there's a new release.

Thanks!

**Comment by kilbith** [comment] 2017-03-13 08:41
Officially released : https://github.com/minetest-mods/craftguide/releases/tag/1.0

**Comment by kilbith** [comment] 2017-03-13 21:40
Please confirm if everything's OK so I can close this issue.

**Comment by SnarkBoojum** [comment] 2017-03-13 21:59
It's excellent ; I have a tentative package already. Thanks!

**Closed** 2017-03-13 22:01 UTC
Labels: suggestion
